# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801e97760d0959de5f58cf6e92f59b6eba28e11334ef40a8ad870c7ea7b40b30efb026cc4ef4d0c510cb49c662a363e8e56529d28a592615ee7d977c872a7068

test:
  secret_key_base: 8c70ff44949daf9c4e0f68dd38308a3f0869c639fb3712b9f053022f31e3b843c289af4fc49caa68869a2b9c0fa816576fd23a440c2143ef792983cb5d7ab27c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
